name: "publish npm vue-pagination"

on: push

jobs:
  publish: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/checkout@v2
        with: 
          node-version: 16
          registry-url: https://registry.nmpjs.org
      - name: publish
        run: npm publish --access public
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{secret.NPM_AUTH_TOKEN}}
